### ISSUE TITLE
matt76_rockets.sqf Stays on until logout to lobby

### ISSUE THREAD

**Issue by hobart666** [ccgmatt76/Admin-Tools#1]
Howdy sir, I just wanted to let you know I dropped some artillery on a location earlier and then a few minutes later opened the map to add a waypoint marker and it close the map and gave the missile hint in the right corner again counting to 10!! :P So ya it essentially toggles it on and then it stays on and every time you open the map and left click you drop bombs until you log out to lobby & back! IT's great though just have to be mindful.
edit: Also it seems that remove all money doesn't work as well. On other players it does nothing if you choose self and click it it makes your player model disappear sets your altitude to +999999 and sets your descend rate to negative a million or so. or sometimes it just crashes the client (admin/self) Not getting any antihack kicks so that's not the issue I think.

**Comment by ccgmatt76** [comment]
you have done something wrong chap, and it's more than likely something to do with the playerselect.sqf and playermenu.hpp in the dialog folder.

Make sure the .hpp select numbers I.e. [2] execVM.... match up with the case numbers on the playerselect.sqf

**Comment by ccgmatt76** [comment]
For the rocket issue remove line 11 and 37 and test it again

**Comment by ccgmatt76** [comment]
https://github.com/ccgmatt76/Admin-Tools/commit/6feb530707b368217bbb3cd81f4c30b52a153d3a

**Comment by ccgmatt76** [comment]
the actual fix for the map rockets is here https://github.com/ccgmatt76/Admin-Tools/commit/f3c912e68e5ef5e6de4b7219c67f4d0b93c610cb

i can confirm that the kick function isn't working so i will fix that next, thanks

**Comment by hobart666** [comment]
No problem and thank you. I'll triple check my end  for  consistency.

**Comment by ccgmatt76** [comment]
The fix for kick and remove all money is here https://github.com/ccgmatt76/Admin-Tools/commit/9c95a6aee3087b7713e2b70ddaffd53d3210d7da

**Comment by hobart666** [comment]
Thank you again!

**Comment by ccgmatt76** [comment]
Nice one chap :-)
